# Generated by Django 5.2.7 on 2025-11-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaferData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dot_number", models.TextField(blank=True, null=True)),
                ("legal_name", models.TextField(blank=True, null=True)),
                ("physical_address", models.TextField(blank=True, null=True)),
                ("zipcode", models.TextField(blank=True, null=True)),
                ("mailing_code", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("operating_status", models.TextField(blank=True, null=True)),
                ("power_units", models.TextField(blank=True, null=True)),
                ("drivers", models.TextField(blank=True, null=True)),
                ("date_filed", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("fetched_at", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "safer_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
